### ISSUE TITLE
Change default color of titles

### ISSUE THREAD

**Issue by larsenwork** [sonburn/symbol-organizer#99]
Current color is `#000000` but it's really hard to read in dark mode where the background by default is `#1D1E1F` 

Using something like `#7F7F7F` would make it work in both dark mode and default mode.

**Comment by sonburn** [comment]
@larsenwork Thanks for the suggestion. I just published an update (15.5) which addresses this. To keep things simple for now, I simply changed the default font color to white if using a dark theme. You can always customize it once it's established in your document.

**Comment by n0k5** [comment]
Not using the dark theme but still getting the white labels.

I'm using 10.12.6 (Sierra) and have the dark dock enabled, but not the dark theme in Sketch, if that helps.

**Comment by sonburn** [comment]
@n0k5 Did you originally have dark theme enabled when the style got created in the document? If so, the style would still be white until you change it, or delete it completely and it gets recreated.

**Comment by larsenwork** [comment]
Id still vote form #7F7F7F since you might be working in a team where only some members are in dark mode :)

**Comment by sonburn** [comment]
@larsenwork You can change the style once it's established in your document, and it should be respected (if it's being overwritten, let me know). If I change the default style per your suggestion, and there are users out there whom would prefer either black or white, then I just created a task for them to update the style every time it gets created as well. An alternative solution might be to offer a default color value field, I can consider this. Thank you for your feedback.

**Comment by srouse** [comment]
+1 on getting white labels on a Mac not using dark theme (they are invisible on the light grey bg). I have been updating the style (to black) manually, but each time I reorder titles go back to white. Computer is brand new....it's never been in dark mode.

**Comment by SlackroPixie** [comment]
Hi-

Great plugin- but this recent update is really slowing me down and is frustrating. I am also getting white labels, am not using the dark theme. Cannot see the labels and have to change it every single time I reconfigure. 

Have tried to change the color and update the default type style. Tried to detach default layer style & then create & assign a new type style with dark color. Then made sure I  assigned it again in the reconfigure box, Tried restart/reinstall....nothing works. Type remains white and is very difficult to read. Please let me know if this is possible to change. I loved using it before, now its not nearly as easy for me to quickly navigate the page.Thanks

**Comment by sonburn** [comment]
@srouse, @SlackroPixie, sorry you are having issues. It seems I am unable to reproduce this circumstance no matter what I try. Within Sketch could you copy/paste the following in Plugins > Run Script and click the Run button, and let me know what the result is (either 1 or 0)?

'''
log(NSUserDefaults.standardUserDefaults().stringForKey("AppleInterfaceStyle") == "Dark" ? true : false)
'''
